config/routes.rb
Rails.application.routes.draw do
  resources :zombies

  root 'zombies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/zombie.rb
class Zombie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  before_action :set_zombie, only: [:show, :edit, :update, :destroy]

  # GET /zombies
  # GET /zombies.json
  def index
    @zombies = Zombie.all
  end

  # GET /zombies/1
  # GET /zombies/1.json
  def show
  end

  # GET /zombies/new
  def new
    @zombie = Zombie.new
  end

  # GET /zombies/1/edit
  def edit
  end

  # POST /zombies
  # POST /zombies.json
  def create
    @zombie = Zombie.new(zombie_params)

    respond_to do |format|
      if @zombie.save
        format.html { redirect_to @zombie, notice: 'Zombie was successfully created.' }
        format.json { render :show, status: :created, location: @zombie }
      else
        format.html { render :new }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zombies/1
  # PATCH/PUT /zombies/1.json
  def update
    respond_to do |format|
      if @zombie.update(zombie_params)
        format.html { redirect_to @zombie, notice: 'Zombie was successfully updated.' }
        format.json { render :show, status: :ok, location: @zombie }
      else
        format.html { render :edit }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zombies/1
  # DELETE /zombies/1.json
  def destroy
    @zombie.destroy
    respond_to do |format|
      format.html { redirect_to zombies_url, notice: 'Zombie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zombie
      @zombie = Zombie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zombie_params
      params.require(:zombie).permit(:weight, :kills, :weapon, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/zombies_helper.rb
module ZombiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZombieAttack</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width-device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar'%>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></  script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></  script>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="#">Zombies <span class="sr-only">(current)</span></a>
      <a class="nav-item, text-right"><%= link_to 'New Zombie', new_zombie_path, class:'nav-link active' %><span class="sr-only">(current)</span></a>
    </div>
    </div>
  </div>
</nav>

app/views/zombies/_form.html.erb
<div class="row">
<div class="col-md-6 offset-md-3">
<%= form_with(model: zombie, local: true) do |form| %>
  <% if zombie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(zombie.errors.count, "error") %> prohibited this zombie from being saved:</h2>

      <ul>
      <% zombie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
   <%#> <%= form.label :weight %>
    <%= form.number_field :weight, class: 'form-control', placeholder:"weight" %>
  </div>

  <div class="form-group">
    <%#> <%= form.label :kills %>
    <%= form.number_field :kills, class: 'form-control', placeholder:"kills" %>
  </div>

  <div class="form-group">
    <%#><%= form.label :weapon %>
    <%= form.text_field :weapon, class: 'form-control', placeholder:"weapon" %>
  </div>

  <div class="form-group">
    <%#><%= form.label :picture %>
    <%= form.text_field :picture, class: 'form-control', placeholder:"weapon" %>
  </div>

  <div class="actions">
    <%= form.submit class:'btn btn-primary' %>
  </div>
<% end %>
</div>
</div>

app/views/zombies/edit.html.erb
<h1 class="text-center">Editing Zombie</h1>

<%= render 'form', zombie: @zombie %>
<div class="offset-md-3">
<%= link_to 'Show', @zombie %> 
<%= link_to 'Back', zombies_path %>
</div>

app/views/zombies/index.html.erb
<h1 class='text-center'>Zombies paradise</h1>

<% @zombies.each_slice(3) do |three_zombies|%>
  <div class= "card-deck">
   <% three_zombies.each do |zombie| %>  
    <div class="card" style="width: 18rem;">
      <%= image_tag zombie.picture, class:'card-img-top img-fluid', alt:"zombie" %>
      <div class="card-body">
        <h5 class="card-title"><%= zombie.weight  %></h5>
        <h5 class="card-title"><%= zombie.kills %></h5>
        <h5 class="card-title"><%= zombie.weapon %></h5>
        <%= link_to 'Show', zombie, class:'btn btn-primary' %>
        <%= link_to 'Edit', edit_zombie_path(zombie), class:'btn btn-info' %>
        <%= link_to 'Destroy', zombie, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn    btn-danger' %>  
      </div>
    </div>    
     
    <% end %>
  </div>
<% end %>
<br>

app/views/zombies/new.html.erb
<h1 class="text-center">New Zombie</h1>

<%= render 'form', zombie: @zombie %>

<%= link_to 'Back', zombies_path %>

app/views/zombies/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
<div class="col-md-6 offset-md-3">
<div class="card" style="width: 28rem;">
   <%= image_tag @zombie.picture, class:'card-img-top', alt:'zombie'%>
  <div class="card-body">
    <h5 class="card-title"> <%= @zombie.weight %></h5>
    <h5 class="card-title"> <%= @zombie.kills %></h5>
    <h5 class="card-title"> <%= @zombie.weapon %></h5>
    <%= link_to 'Edit', edit_zombie_path(@zombie), class:'btn btn-info' %> 
    <%= link_to 'Back', zombies_path, class:'btn btn-info' %>
  </div>
</div>
</div>
</div>